/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import dao.DoctorOperationDao;
import dao.DrugDao;
import dao.DrugStockDao;
import dao.GetDrugDao;
import dao.PatientCheckDao;
import dao.PatientDrugDao;
import entity.Doctor;
import entity.Drug;

import entity.DrugGet;
import entity.PatientBuy;
import entity.PatientBuyExt;
import entity.PatientCheck;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class GetDrugForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form GetDrugForm
     */
    public GetDrugForm() {
        initComponents();
        
        init();
    }
    
    public void init(){
         DefaultTableModel tablePatient = (DefaultTableModel) jTablePatient.getModel();
         tablePatient.setRowCount(0);
         
         PatientCheckDao patientCheckDao = new PatientCheckDao();
         List<PatientCheck> patientCheckList = patientCheckDao.getAllPatientCheck();
         
          for (int i = 0; i < patientCheckList.size(); i++){
            PatientCheck patientCheck = patientCheckList.get(i);
            tablePatient.addRow(new Object[]{patientCheck.getPatientID(), patientCheck.getPatientName(),
                patientCheck.getGetFlag()});
        }
  
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDrug = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "用户ID", "用户姓名", "拿药状态"
            }
        ));
        jTablePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTablePatientMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePatient);

        jTableDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "药品ID", "药品名称", "需求", "库存"
            }
        ));
        jTableDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableDrugMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDrug);

        jButton1.setText("拿药");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        // TODO add your handling code here:
        int row = jTablePatient.getSelectedRow();
        int drugID = 0;
        int drugNum = 0;
        int patientID = Integer.parseInt(jTablePatient.getValueAt(row, 0).toString());
        GetDrugDao getDrugDao = new GetDrugDao();
        int flag = getDrugDao.updateDrugGet(patientID);
//        int drugIDRowCount = jTableDrug.getRowCount();

        
        if(flag == 1){
            DrugStockDao drugStockDao = new DrugStockDao();
            List<PatientBuy> drugsIDANDNum = drugStockDao.GetdrugListWithPID(patientID);
            for(int i = 0; i<drugsIDANDNum.size(); i++){
                drugID = drugsIDANDNum.get(i).getDrugID();
                
                drugNum = drugsIDANDNum.get(i).getDrugNum();
//                System.out.println(drugID);
//                System.out.println(drugNum);
                drugStockDao.drugStockUpdate(drugID, drugNum);
//                drugStockDao.drugStockUpdate(1, 101);
            }
            
//            for(int i = 0; i<drugIDListWithPID.length; i++){
//                System.out.println(drugIDListWithPID[i]);
//            }
//            for(int i = 0; i<=drugIDRowCount; i++){
////                drug
////                drugID = Integer.parseInt(jTableDrug.getValueAt(drugID, 0).toString());
////                Drug drug = null;
//        
//               
//            }
            
             JOptionPane.showMessageDialog(null,"取药成功");
             DefaultTableModel tableDrug = (DefaultTableModel) jTablePatient.getModel();
             tableDrug.setRowCount(0);
        }else{
          JOptionPane.showMessageDialog(null,"取药失败");
        }
        init();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableDrugMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDrugMouseReleased
        // TODO add your handling code here:
//         int row =jTablePatient.getSelectedRow();
//           int id = Integer.parseInt(jTablePatient.getValueAt(row, 0).toString());
////           int drugID=Integer.parseInt(jTableDrug.getValueAt(row,1).toString());
////           int drugNum=Integer.parseInt(jTableDrug.getValueAt(row,2).toString());
////           int drugStock=Integer.parseInt(jTableDrug.getValueAt(row,3).toString());
//       
//         DefaultTableModel model=(DefaultTableModel)jTableDrug.getModel();
////         model.setRowCount(0);
//         
//       PatientBuyDao patientBuyDao = new PatientBuyDao();
//       List<PatientBuy> patientBuyList = patientBuyDao.getPatientBuy(id);
//          for (int i=0;i<patientBuyList.size();i++){
//            PatientBuy PatientBuy =patientBuyList.get(i);
//             model.addRow(new Object[]{PatientBuy.getDrugID(),PatientBuy.getPatientID(),
//                 PatientBuy.getDrugNum()});
//         }
          
//            DefaultComboBoxModel comModel= ( DefaultComboBoxModel )jTableDrug.getModel();
//         GetDrugDao getdrugDao = new GetDrugDao();
//         List<DrugGet> getdrugs = getdrugDao.getDrugGet();
//         for(int i =0;i<getdrugs.size();i++){
//             DrugGet getdrug = getdrugs.get(i);
//             comModel.addElement(getdrug);
//         }
    }//GEN-LAST:event_jTableDrugMouseReleased

    private void jTablePatientMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientMouseReleased
    //         TODO add your handling code here:
        int row =jTablePatient.getSelectedRow();
        int id = Integer.parseInt(jTablePatient.getValueAt(row, 0).toString());
        
        System.out.println(row);
       
         DefaultTableModel model2=(DefaultTableModel)jTableDrug.getModel();
         model2.setRowCount(0);
         
        PatientDrugDao patientDrugDao = new PatientDrugDao();
        List<PatientBuyExt> patientBuyExtList = patientDrugDao.getPatientBuyAndDrug(id);
        System.out.println(patientBuyExtList.size());
        
          for (int i=0;i<patientBuyExtList.size();i++){
            PatientBuyExt patientBuyExt =patientBuyExtList.get(i);
             model2.addRow(new Object[]{patientBuyExt.getDrugID(),patientBuyExt.getDrugName(),patientBuyExt.getDrugNum(),  patientBuyExt.getDrugStock()});
         }
//          
//          
//           int row =jTableDrug.getSelectedRow();
//           int id = Integer.parseInt(jTableDrug.getValueAt(row, 0).toString());
//           /*int drugID=Integer.parseInt(jTableDrug.getValueAt(row,1).toString());
//           int drugNum=Integer.parseInt(jTableDrug.getValueAt(row,2).toString());
//           int drugStock=Integer.parseInt(jTableDrug.getValueAt(row,3).toString());
//        */
//         DefaultTableModel model=(DefaultTableModel) jTablePatient.getModel();
//         model.setRowCount(0);
//         
//       PatientBuyDao patientBuyDao = new PatientBuyDao();
//       List<PatientBuy> patientBuyList = patientBuyDao.getPatientBuy(id);
//          for (int i=0;i<patientBuyList.size();i++){
//            PatientBuy PatientBuy =patientBuyList.get(i);
//             model.addRow(new Object[]{PatientBuy.getDrugID(),PatientBuy.getPatientID(),
//                 PatientBuy.getDrugNum()});
//         }
    }//GEN-LAST:event_jTablePatientMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDrug;
    private javax.swing.JTable jTablePatient;
    // End of variables declaration//GEN-END:variables
}
