/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import dao.HosDao;
import dao.PatientCaseDao;
import dao.PatientDao;

import entity.Patient;
import entity.PatientBuy;
import entity.PatientCase;
import entity.PatientCaseExt;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PatientListForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManagaCheckForm
     */
    public PatientListForm() {
        initComponents();
        
        setLocation(100, 100);
        
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        PatientDao patientDao = new PatientDao();
        List<Patient> patients = patientDao.getPatients();
        
        for(int i = 0; i<patients.size();i++){
            Patient patient = patients.get(i);
            
            model.addRow(new Object[]{patient.getPatientID(),patient.getPatientName(), patient.getPatientAge(),patient.getPatientSex(),patient.getPatientAllergic(),patient.getDepartmentName(),patient.getDoctorName()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "病人编号", "名字", "年龄", "性别", "过敏史", "科室", "主治医师"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "病因", "治疗方案"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "药品编号", "药品名", "药品所需数量"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
       
        
        int row = jTable1.getSelectedRow();
        int patientID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        
        
          DefaultTableModel model3 = (DefaultTableModel)jTable3.getModel();
        model3.setRowCount(0);
        HosDao hosDao2 = new HosDao();
         List<PatientBuy> pbList = hosDao2.getPatientBuy(patientID);
                 for(int i = 0; i<pbList.size();i++){
            PatientBuy pb = pbList.get(i);
            
            model3.addRow(new Object[]{pb.getDrugID(),pb.getDrugName(), pb.getDrugNum()});
        }
        
        DefaultTableModel model2 = (DefaultTableModel)jTable2.getModel();
        model2.setRowCount(0);
     
        HosDao hosDao = new HosDao();
        List<PatientCase> pcList = hosDao.getPatientCase(patientID);

        for(int i = 0; i<pcList.size();i++){
            PatientCase pc = pcList.get(i);
            
            model2.addRow(new Object[]{pc.getIllnessCase(),pc.getPatientSolve()});
        }
        
      
    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
