/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import dao.DoctorOperationDao;
import dao.PatientDao;
import entity.Doctor;
import entity.Patient;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class RegsiterModifyForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegsiterModifyForm
     */
    public RegsiterModifyForm() {
        initComponents();
        setLocation(50,50);
       
}
    public void init(){
            DefaultTableModel mdoel1 =  (DefaultTableModel) jTable1.getModel();
        mdoel1.setRowCount(0);
        
        int Tid =  Integer.parseInt(jtId.getText());
       PatientDao patientDao = new PatientDao();
        
        List<Patient> patientList = patientDao.selectPatient(Tid);
        
        for(int i =0; i < patientList.size(); i++){
           Patient patient = patientList.get(i);
            mdoel1.addRow(new Object[]{patient.getPatientID(), patient.getPatientName(), patient.getPatientSex(),
                patient.getPatientAge(), patient.getPatientAllergic(), patient.getDepartmentName(), patient.getDoctorName()});
        
        }
         DefaultComboBoxModel modelDepartment = (DefaultComboBoxModel)jcDepartment.getModel();
         //获取科室信息
        DoctorOperationDao patientDepartments = new DoctorOperationDao();
            
        List<Doctor> patientDepartmentList = patientDepartments.getAllDoctor();
        
        for(int i = 0; i<patientDepartmentList.size();i++){
            Doctor doctor = patientDepartmentList.get(i);
            modelDepartment.addElement(doctor.getDepartmentName());
        }
        
         //获取医生信息
        DefaultComboBoxModel modelDoctor = (DefaultComboBoxModel)jcDoctor.getModel();
        DoctorOperationDao patientDoctor = new DoctorOperationDao();
        List<Doctor> patientDoctorLIst = patientDoctor.getAllDoctor();
        
        for(int i = 0; i < patientDoctorLIst.size(); i++){
            Doctor doctor = patientDoctorLIst.get(i);
            modelDoctor.addElement(doctor.getDoctorName());
        }
       
        
      
        int row=0;
        String id=jTable1.getValueAt(row, 0).toString();
        String name=jTable1.getValueAt(row, 1).toString();
        String sex=jTable1.getValueAt(row, 2).toString();
        String age=jTable1.getValueAt(row, 3).toString();
        String allergic=jTable1.getValueAt(row, 4).toString();
        String departmentName=jTable1.getValueAt(row,5).toString();
        String doctorName=jTable1.getValueAt(row, 6).toString();
        
        jtId.setText(id);
        jtName.setText(name);
        jtSex.setText(sex);
        jtAge.setText(age);
        jtAllergic.setText(allergic);
        jcDepartment.setSelectedItem(departmentName);
        jcDoctor.setSelectedItem(doctorName);  
           
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jButtonSelect = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtName = new javax.swing.JTextField();
        jtAge = new javax.swing.JTextField();
        jtSex = new javax.swing.JTextField();
        jtAllergic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcDepartment = new javax.swing.JComboBox<>();
        jcDoctor = new javax.swing.JComboBox<>();

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "编号", "姓名", "性别", "年龄", "过敏史", "科室", "医生"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("编号：");

        jButtonSelect.setText("查询");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("修改");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("删除");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("姓名：");

        jLabel2.setText("性别 ：");

        jLabel3.setText("年龄：");

        jLabel4.setText("过敏史 ：");

        jLabel5.setText("科室：");

        jtAllergic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAllergicActionPerformed(evt);
            }
        });

        jLabel6.setText("医生：");

        jcDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDepartmentActionPerformed(evt);
            }
        });

        jcDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtName)
                            .addComponent(jtAge)
                            .addComponent(jcDepartment, 0, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtSex)
                            .addComponent(jtAllergic)
                            .addComponent(jcDoctor, 0, 116, Short.MAX_VALUE))
                        .addContainerGap(292, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSelect)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDelete)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSelect)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtAllergic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAllergicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAllergicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAllergicActionPerformed

    private void jcDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDepartmentActionPerformed

    private void jcDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDoctorActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        // TODO add your handling code here:

        init();
        
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
          int row=jTable1.getSelectedRow();
        String id=jTable1.getValueAt(row, 0).toString();
        String name=jTable1.getValueAt(row, 1).toString();
        String sex=jTable1.getValueAt(row, 2).toString();
        String age=jTable1.getValueAt(row, 3).toString();
        String allergic=jTable1.getValueAt(row, 4).toString();
        String departmentName=jTable1.getValueAt(row,5).toString();
        String doctorName=jTable1.getValueAt(row, 6).toString();
        
        jtId.setText(id);
        jtName.setText(name);
        jtSex.setText(sex);
        jtAge.setText(age);
        jtAllergic.setText(allergic);
        jcDepartment.setSelectedItem(departmentName);
        jcDoctor.setSelectedItem(doctorName);  
     
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        
        
        String name=jtName.getText();
        String sex=jtSex.getText();
        String age=jtAge.getText();
        String allergic=jtAllergic.getText();
        String departmentName=jcDepartment.getSelectedItem().toString();
        String doctorName=jcDoctor.getSelectedItem().toString();
      
        Patient patient=new Patient();
        
        patient.setPatientName(name);
        patient.setPatientSex(sex);
        patient.setPatientAge(Integer.parseInt(age));
        patient.setPatientAllergic(allergic);
        patient.setDepartmentName(departmentName);
        patient.setDoctorName(doctorName);
        
        PatientDao  patientDao =new PatientDao();
         int ID =  Integer.parseInt(jtId.getText());

        
        int row = patientDao.updatePatient(patient, ID);
        
        if(row == 1){
             JOptionPane.showMessageDialog(null,"修改成功");
             init();
           
        }else{
          JOptionPane.showMessageDialog(null,"修改失败");
        }
        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtId.getText());
        String name=jtName.getText();
        String sex=jtSex.getText();
        String age=jtAge.getText();
        String allergic=jtAllergic.getText();
        String departmentName=jcDepartment.getSelectedItem().toString();
        String doctorName=jcDoctor.getSelectedItem().toString();
      
        Patient patient=new Patient();
        
        patient.setPatientID(id);
        patient.setPatientName(name);
        patient.setPatientSex(sex);
        patient.setPatientAge(Integer.parseInt(age));
        patient.setPatientAllergic(allergic);
        patient.setDepartmentName(departmentName);
        patient.setDoctorName(doctorName);
        
        PatientDao  patientDao =new PatientDao();
        
        
       
        int row = patientDao.deletePatient(patient);
        
        if(row == 1){
            JOptionPane.showMessageDialog(null,"删除成功");
            DefaultTableModel mdoel1 =  (DefaultTableModel) jTable1.getModel();
            mdoel1.setRowCount(0);
           
        }else{
          JOptionPane.showMessageDialog(null,"删除失败");
        }
        
        
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcDepartment;
    private javax.swing.JComboBox<String> jcDoctor;
    private javax.swing.JTextField jtAge;
    private javax.swing.JTextField jtAllergic;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtName;
    private javax.swing.JTextField jtSex;
    // End of variables declaration//GEN-END:variables
}
