/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TypeDao;
import dao.UpdateTypeDao;
import entity.BookType;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class ManageType extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageType
     */
    public ManageType() {
        initComponents();
        init();
        
    }
    
    public void init(){
        DefaultTableModel model = (DefaultTableModel)BookType.getModel();
        model.setRowCount(0);
        TypeDao typeDao = new TypeDao();
        List<BookType> types = typeDao.getTypes();

        for(int i=0; i<types.size(); i++){
            BookType bookType = types.get(i);
            model.addRow(new Object[]{bookType.getBookNo(), bookType.getBookName()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookType = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BookTypeID = new javax.swing.JTextField();
        BookTypeName = new javax.swing.JTextField();
        jBUpdate = new javax.swing.JButton();

        BookType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookTypeID", "BookTypeName"
            }
        ));
        BookType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BookTypeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(BookType);

        jLabel1.setText("BookTypeID");

        jLabel2.setText("BookTypeName");

        BookTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTypeIDActionPerformed(evt);
            }
        });

        jBUpdate.setText("Update");
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBUpdate)
                                    .addComponent(BookTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BookTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BookTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jBUpdate)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTypeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTypeIDActionPerformed

    private void BookTypeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTypeMouseReleased
        // TODO add your handling code here:
        int row = BookType.getSelectedRow();
        
        BookTypeID.setText(BookType.getValueAt(row, 0).toString());
        BookTypeName.setText(BookType.getValueAt(row, 1).toString());
    }//GEN-LAST:event_BookTypeMouseReleased

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed
        // TODO add your handling code here:
        String newID = BookTypeID.getText();
        String newName = BookTypeName.getText();
        BookType bookType = new BookType();
        bookType.setBookNo(Integer.parseInt(newID));
        bookType.setBookName(newName);
        
        UpdateTypeDao updateTypeDao = new UpdateTypeDao();
        int row = updateTypeDao.updateType(bookType);
        
        if(row == 1){
            JOptionPane.showMessageDialog(null, "成功");
            init();
        }else{
            JOptionPane.showMessageDialog(null, "失败");
        }
    }//GEN-LAST:event_jBUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookType;
    private javax.swing.JTextField BookTypeID;
    private javax.swing.JTextField BookTypeName;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
